export const CLIENT_INFORMATION_REQUEST = 'CLIENT_INFORMATION_REQUEST'
export const CLIENT_INFORMATION_SUCCESS = 'CLIENT_INFORMATION_SUCCESS'
export const CLIENT_INFORMATION_FAIL = 'CLIENT_INFORMATION_FAIL'


export enum ActionType {
  CLIENT_INFORMATION_REQUEST = 'CLIENT_INFORMATION_REQUEST',
  CLIENT_INFORMATION_SUCCESS = 'CLIENT_INFORMATION_SUCCESS',
  CLIENT_INFORMATION_FAIL = 'CLIENT_INFORMATION_FAIL'
}