# Generated by Django 3.2.6 on 2021-10-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogsection',
            options={'ordering': ('id',), 'verbose_name_plural': 'Blog Sections'},
        ),
        migrations.CreateModel(
            name='BlogReadingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=100)),
                ('link_url', models.URLField()),
                ('article_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogsection')),
            ],
            options={
                'verbose_name_plural': 'Blog Reading Links',
                'ordering': ('id',),
            },
        ),
    ]
