# Generated by Django 3.2.6 on 2021-10-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211030_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogreadinglink',
            old_name='article_title',
            new_name='section_title',
        ),
    ]
