# Generated by Django 3.2.6 on 2021-11-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogsectionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSectionCodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_title', models.CharField(max_length=100)),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('section_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogsection')),
            ],
            options={
                'verbose_name_plural': 'Code Snippets',
                'ordering': ('id',),
            },
        ),
    ]
