# Generated by Django 3.2.6 on 2021-11-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogsectioncodesnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSectionTerminalCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_title', models.CharField(max_length=100)),
                ('command_icon', models.CharField(max_length=100)),
                ('command', models.TextField(blank=True, null=True)),
                ('section_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogsection')),
            ],
            options={
                'verbose_name_plural': 'Terminal Commands',
                'ordering': ('id',),
            },
        ),
    ]
