# Generated by Django 3.2.6 on 2021-08-15 09:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210812_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'About me',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('deployed_url', models.CharField(max_length=500)),
                ('github_url', models.CharField(max_length=500)),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.aboutme')),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='SkillCapabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.aboutme')),
            ],
            options={
                'verbose_name_plural': 'Skills-Capabilities',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(max_length=300)),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.aboutme')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('institute_name', models.CharField(max_length=150)),
                ('institute_link', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.aboutme')),
            ],
            options={
                'verbose_name_plural': 'Education_details',
            },
        ),
    ]
