# Generated by Django 3.2.6 on 2021-08-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_aboutme_education_skill_skillcapabilities_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployed_url_icon',
            field=models.CharField(default='add icon name', max_length=150),
        ),
    ]
