# Generated by Django 3.2.6 on 2021-10-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211016_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['display_order', 'pk'], 'verbose_name_plural': 'Experiences'},
        ),
    ]
