# Generated by Django 3.2.6 on 2021-11-06 11:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_workexperience_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image.jpg', max_length=255, verbose_name='image'),
        ),
    ]
