# Generated by Django 3.2.6 on 2022-01-30 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_contactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
